# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E6DEE3
background         #06000A
cursor             #CF9DB5

active_tab_foreground     #06000A
active_tab_background     #E6DEE3
inactive_tab_foreground   #E6DEE3
inactive_tab_background   #06000A

active_border_color   #E6DEE3
inactive_border_color #06000A
bell_border_color     #405441

color0      #110913
color1		#405441
color2		#8A4665
color3		#5E7F8B
color4		#6C7D88
color5		#887884
color6		#8B7883
color7		#D4C7CF
color8		#948B91
color9		#557057
color10		#B85D87
color11		#7EA9B9
color12		#90A6B6
color13		#B5A1B0
color14		#B9A0AF
color15		#D4C7CF
